ersion: "3.7"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fetch_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
